### ISSUE TITLE
FEATURE: Epic 11 - F2

### ISSUE THREAD

**Issue by obenedek20** [ucsb-cs156-f24/proj-rec-f24-08#28]
F2: Create Request Page + Form Component 
- [ ] There is a button on the Student Profile page to create a new request. This button leads to a page where the student can fill out a form for a new request.
- [ ] Form component is implemented in the frontend.
- [ ] Create Request Button is implemented and leads to a Create Request Page.
- [ ] Create Request Page has the form that can be filled out by the user.

- [ ] There is adequate test coverage for both the frontend and backend
