### ISSUE TITLE
Epic 14 - B1

### ISSUE THREAD

**Issue by caleb-stahl** [ucsb-cs156-f24/proj-rec-f24-08#45]
- [ ] Ensure that the professor role has the permissions necessary to make post edits to the backend of a request

- [ ] When a pending request is marked as accepted, denied, the dateAcceptedDenied is also saved to the backend

- [ ] When a pending request is marked as accepted, denied, the dateCompleted is also saved to the backend
